/*
 * MyClinic API
 * My nice API to give to other developers
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Telephone;
import java.util.ArrayList;
import java.util.List;

/**
 * Patient
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-14T20:18:46.451Z")
public class Patient {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("telephones")
  private List<Telephone> telephones = new ArrayList<Telephone>();

  @SerializedName("preferredPhone")
  private String preferredPhone = null;

  public Patient id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique global id of this patient.
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "The unique global id of this patient.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Patient name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The patient's full name.
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "The patient's full name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Patient telephones(List<Telephone> telephones) {
    this.telephones = telephones;
    return this;
  }

  public Patient addTelephonesItem(Telephone telephonesItem) {
    this.telephones.add(telephonesItem);
    return this;
  }

   /**
   * Get telephones
   * @return telephones
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Telephone> getTelephones() {
    return telephones;
  }

  public void setTelephones(List<Telephone> telephones) {
    this.telephones = telephones;
  }

  public Patient preferredPhone(String preferredPhone) {
    this.preferredPhone = preferredPhone;
    return this;
  }

   /**
   * The ID of the preferred phone to call this patient.
   * @return preferredPhone
  **/
  @ApiModelProperty(example = "null", value = "The ID of the preferred phone to call this patient.")
  public String getPreferredPhone() {
    return preferredPhone;
  }

  public void setPreferredPhone(String preferredPhone) {
    this.preferredPhone = preferredPhone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Patient patient = (Patient) o;
    return Objects.equals(this.id, patient.id) &&
        Objects.equals(this.name, patient.name) &&
        Objects.equals(this.telephones, patient.telephones) &&
        Objects.equals(this.preferredPhone, patient.preferredPhone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, telephones, preferredPhone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Patient {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    telephones: ").append(toIndentedString(telephones)).append("\n");
    sb.append("    preferredPhone: ").append(toIndentedString(preferredPhone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

