/*
 * MyClinic API
 * My nice API to give to other developers
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Physician
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-14T20:18:46.451Z")
public class Physician {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  public Physician id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique global id of this physician.
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "The unique global id of this physician.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Physician name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The physician's full name.
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "The physician's full name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Physician physician = (Physician) o;
    return Objects.equals(this.id, physician.id) &&
        Objects.equals(this.name, physician.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Physician {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

